spring.application.name=backend
server.port=8080
server.servlet.context-path=/ai-interview

spring.cloud.config.enabled=false

# ================= DATABASE =================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ================= HIKARI =================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.keepalive-time=60000

# ================= MAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================= GOOGLE LOGIN =================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# ================= JWT =================
app.jwt.secret=${JWT_SECRET}

# ================= FRONTEND =================
app.frontend.url=http://localhost:5173

# ================= SUPABASE =================
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}

# ================= RATE LIMIT =================
resilience4j.ratelimiter.instances.chat-limit.limit-for-period=5
resilience4j.ratelimiter.instances.chat-limit.limit-refresh-period=60s
resilience4j.ratelimiter.instances.chat-limit.timeout-duration=0s